name: "test"
on:
  issue_comment:
    types: [created]
jobs:
  buildJDK:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        jdk_version: [11,12,13,15]
        jdk_impl: [hotspot,openj9]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: AdoptOpenJDK/build-jdk@v1
      with:
        javaToBuild: jdk${{ matrix.jdk_version }}u
        impl: ${{ matrix.jdk_impl }}
        usePRRef: false
